# argparse, yaml
# https://www.notion.so/yaml-configuration-a911146bffb04b92abfef8f54e291852
# https://csm-kr.tistory.com/19
# https://velog.io/@leaps/Pytorch-1.-Config-module-%EB%A7%8C%EB%93%A4%EA%B8%B0

TRAIN_DATA:
    train_data_path : 'READ FROM HUGGINGFACE'
    data_name : 'korNLI'

TASK:
    type : 'cls'

TEST_DATA:
    test_data_path : 'READ FROM HUGGINGFACE'

MODEL:
    model_name : 'klue/bert-base' # used for model, tokenizer
    num_labels : 3

TOKENIZER:
    model_name : 'klue/bert-base'
    truncation : True
    max_length : 512

TRAIN:
    num_train_epochs : 1
    train_bs : 32
    eval_bs : 64
    lr : 2e-5
    save_steps: 1000
    eval_steps: 1000
    evaluation_strategy: 'steps'

OUTPUT:
    model_save : './results'

LOGGING:
    logging_dir: './logs'
    logging_steps : 500
    save_total_limit : 2
    wandb : False

ETC:
    seed : 42


